#!/usr/bin/env bash

# Copyright The Rusted Firmware-A Contributors.
#
# SPDX-License-Identifier: BSD-3-Clause

# Make sure `cargo vet` and `cargo clippy` are clean, and everything builds,
# before `git push`.

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s extdebug

vet=$(cargo --list | awk '$1 == "vet" { print $1 }')
if [[ "$vet" != "vet" ]]; then
    cargo install cargo-vet
fi

clippy=$(cargo --list | awk '$1 == "clippy" { print $1 }')
if [[ "$clippy" != "clippy" ]]; then
    rustup component add clippy-preview
fi

must() {
    if ! $@; then
        echo -- "$@" > /dev/stderr
        exit 1
    fi
}

must cargo test
must make clippy-test

# NOTE: If we add even a few more supported configurations, we're going to want a permutation
# function to generate them all.
for platform in qemu fvp; do
    for debug in 1 0; do
        declare -a all_features=("" "sel2" "rme" "sel2 rme")
        if [[ "$platform" == "qemu" ]]; then
            all_features=("" "sel2")
        fi
        for features in "${all_features[@]}"; do
            echo "platform: $platform, debug: $debug, features: $features"
            if [[ -z "$features" ]]; then
                must make DEBUG="$debug" PLAT="$platform" FEATURES= build
            else
                export FEATURES="$features"
                must make DEBUG="$debug" PLAT="$platform" build
            fi
        done
    done
    must make PLAT="$platform" clippy
done

must cargo vet
must cargo fmt
