[package]
name = "tf-a-bl31"
version = "0.1.0"
edition = "2021"
authors = [
  "Andrew Walbran <qwandor@google.com>",
  "Okash Khawaja <okash@google.com>",
]

[dependencies]
aarch64-paging = "0.6.0"
bitflags = "2.3.2"
buddy_system_allocator = "0.9.1"
log = "0.4.19"
spin = { version = "0.9.8", default-features = false, features = [
  "once",
  "spin_mutex",
] }

[build-dependencies]
cc = "1.0.79"
